name: Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # (Opsional tapi disarankan) Set up Android SDK + accept licenses
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Pastikan Gradle wrapper ada
      - name: Show Gradle Wrapper version
        run: |
          chmod +x ./gradlew
          ./gradlew --version

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
